image: node:12.16.3-buster-slim

before_script:
    - apt-get update -qq && apt-get install

stages:
    - deploy-heroku
    # - build
    # - deploy-digitalocean

cache:
    paths:
        - node_modules/

Deploy-to-heroku:
    image: ruby:2.7.1
    stage: deploy-heroku
    script:
        - apt-get update -qy
        - apt-get install -y ruby-dev
        - gem install dpl
        - wget -qO- https://cli-assets.heroku.com/install-ubuntu.sh | sh
        - dpl --provider=heroku --app=${DEPLOYMENT_NAME_STAGING} --api-key=${HEROKU_API}
    only:
        - staging

# install_dependencies:
#     stage: build
#     script:
#         - npm install
#     artifacts:
#         paths:
#             - node_modules/

# Deploy-to-digitalocean:
#     image: node:latest
#     stage: deploy-digitalocean
#     # environment:
#     #     name: staging
#     #     url: theknowledgeapp.com
#     before_script:
#         - apt-get update -qq
#         - apt-get install -qq git
#         # Setup SSH deploy keys
#         - 'which ssh-agent || ( apt-get install -qq openssh-client )'
#         - eval $(ssh-agent -s)
#         - ssh-add <(echo "$SSH_PRIVATE_KEY")
#         - mkdir -p ~/.ssh
#         - '[[ -f /.dockerenv ]] && echo -e "Host *\n\tStrictHostKeyChecking no\n\n" > ~/.ssh/config'
#     script:
#         - ssh -i ${} {$SSH_USERNAME}@{$SSH_IP} "cd /var/www/{path-to-project} && git checkout dev && git pull origin staging && npm run build && exit"
#     only :
#         - staging


# Build to Staging:
#   stage: build-staging
#   environment:
#     name: development
#   before_script:
#     - yarn
#   script:
#     - npx netlify-cli build
#   only:
#     - staging

# Deploy to Staging:
#   stage: deploy-staging
#   environment:
#     name: development
#     url: https://brives-staging.netlify.app
#   only:
#     - staging
#   before_script:
#     - yarn
#   script:
#     - yarn run build
#     - npx netlify-cli deploy --site $NETLIFY_SITE_ID --auth $NETLIFY_AUTH_TOKEN --prod
