image: node:latest

before_script:  
  - apt-get update -qq && apt-get install

stages:
  # - build-staging
  - deploy-staging


# Build to Staging:
#   stage: build-staging
#   environment:
#     name: development
#   before_script: 
#     - yarn
#   script:
#     - npx netlify-cli build
#   only:
#     - staging


Deploy to Staging:
  stage: deploy-staging
  environment:
    name: development
    url: https://brives-staging.netlify.app
  only:
    - staging
  before_script: 
    - yarn
  script:
    - yarn run build
    - npx netlify-cli deploy --site $NETLIFY_SITE_ID --auth $NETLIFY_AUTH_TOKEN --prod