image: node:12.16.3-buster-slim

before_script:
    - apt-get update -qq && apt-get install

stages:
    - build
    - deploy-heroku
    - deploy-digitalocean

build:
    stage: build
    image: node
    script: 
        - echo "Start building App"
        - npm install
        - CI=false npm run build
        - echo "Build successfully!"
    artifacts:
        paths:
            - build
            - node_modules/
    only:
        - staging

Deploy-to-heroku:
    image: ruby:2.7.1
    stage: deploy-heroku
    script:
        - apt-get update -qy
        - apt-get install -y ruby-dev
        - gem install dpl
        - wget -qO- https://cli-assets.heroku.com/install-ubuntu.sh | sh
        - dpl --provider=heroku --app=${DEPLOYMENT_NAME_STAGING} --api-key=${HEROKU_API}
    only:
        - staging

Deploy-to-digitalocean:
    stage: deploy-digitalocean
    image: docker:latest
    before_script:
        # - apt-get update
        # - 'command -v ssh-agent >/dev/null || ( apt-get update -y && apt-get install openssh-client -y )'
        # - eval $(ssh-agent -s)
        # # - echo "$DIGITALOCEAN_PRIVATE_KEY" | tr -d '\r' | ssh-add -
        # - echo "$DIGITALOCEAN_PRIVATE_KEY" | tr -d '\r' | ssh-add - > /dev/null
        # - mkdir -p ~/.ssh
        # - chmod 700 ~/.ssh
        # - ssh-keyscan gitlab.com >> ~/.ssh/known_hosts
        # - chmod 644 ~/.ssh/known_hosts
        - echo "deploying app"
    script:
        - touch test.txt
        - touch private.key
        - echo "hello world" > test.txt

        - apk add --no-cache bash
        - mkdir -p ~/.ssh
        - echo "$DIGITALOCEAN_PRIVATE_KEY" | tr -d '\r' > ~/.ssh/id_rsa
        - chmod 700 ~/.ssh/id_rsa
        - eval "$(ssh-agent -s)"
        - ssh-add ~/.ssh/id_rsa
        - ssh-keyscan -H 'gitlab.com' >> ~/.ssh/known_hosts
        # - chmod +x ./deploy-staging.sh

        # - echo "REPOSITORY_URL=\"$REPOSITORY_URL\"" | tr -d '\r' >> .env
        # - echo "NODE_ENV=production" | tr -d '\r' >> .env
        # - echo "PORT=8080" | tr -d '\r' >> .env
        # - echo "AWS_ACCESS_KEY_ID=\"$AWS_ACCESS_KEY_ID\"" | tr -d '\r' >> .env
        # - echo "AWS_DEFAULT_REGION=\"$AWS_DEFAULT_REGION\"" | tr -d '\r' >> .env
        # - echo "AWS_SECRET_ACCESS_KEY=\"$AWS_SECRET_ACCESS_KEY\"" | tr -d '\r' >> .env

        - scp -o StrictHostKeyChecking=no test.txt root@$SSH_IP:/testscp
        # - bash ./deploy-staging.sh

        - scp -o StrictHostKeyChecking=no -r ./build root@$SSH_IP:/frontend
        - scp -p22 test.txt root@$SSH_IP:/testscp
        - scp -p22 -r build/* root@$SSH_IP:/frontend
    artifacts:
    # paths:
    #     - build/
    only:
        - adimas

# install_dependencies:
#     stage: build
#     script:
#         - npm install
#     artifacts:
#         paths:
#             - node_modules/

# Deploy-to-digitalocean:
#     image: node:latest
#     stage: deploy-digitalocean
#     # environment:
#     #     name: staging
#     #     url: theknowledgeapp.com
#     before_script:
#         - apt-get update -qq
#         - apt-get install -qq git
#         # Setup SSH deploy keys
#         - 'which ssh-agent || ( apt-get install -qq openssh-client )'
#         - eval $(ssh-agent -s)
#         - ssh-add <(echo "$SSH_PRIVATE_KEY")
#         - mkdir -p ~/.ssh
#         - '[[ -f /.dockerenv ]] && echo -e "Host *\n\tStrictHostKeyChecking no\n\n" > ~/.ssh/config'
#     script:
#         - ssh -i ${} {$SSH_USERNAME}@{$SSH_IP} "cd /var/www/{path-to-project} && git checkout dev && git pull origin staging && npm run build && exit"
#     only :
#         - staging


# Build to Staging:
#   stage: build-staging
#   environment:
#     name: development
#   before_script:
#     - yarn
#   script:
#     - npx netlify-cli build
#   only:
#     - staging

# Deploy to Staging:
#   stage: deploy-staging
#   environment:
#     name: development
#     url: https://brives-staging.netlify.app
#   only:
#     - staging
#   before_script:
#     - yarn
#   script:
#     - yarn run build
#     - npx netlify-cli deploy --site $NETLIFY_SITE_ID --auth $NETLIFY_AUTH_TOKEN --prod
