image: node:latest

stages:
  - deploy

deploy:
  stage: deploy
  environment:
    name: staging
    url: https://brives-staging.netlify.app
  only:
    - staging
  script:
    - npm i
    - yarn install
    - yarn test
    - yarn build
    - npm run build
    - npx netlify-cli deploy --site $NETLIFY_SITE_ID --auth $NETLIFY_AUTH_TOKEN --prod